// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project1.Models;

namespace Project1.Migrations
{
    [DbContext(typeof(FormInfoContext))]
    [Migration("20210317014907_Start")]
    partial class Start
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12");

            modelBuilder.Entity("Project1.Models.FormInfo", b =>
                {
                    b.Property<int>("TourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameOfGroup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<int>("SizeOfGroup")
                        .HasColumnType("INTEGER");

                    b.HasKey("TourId");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("Project1.Models.TimeInfo", b =>
                {
                    b.Property<int>("TimeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.Property<int>("TourId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TimeID");

                    b.HasIndex("TourId")
                        .IsUnique();

                    b.ToTable("Times");
                });

            modelBuilder.Entity("Project1.Models.TimeInfo", b =>
                {
                    b.HasOne("Project1.Models.FormInfo", "FormInfo")
                        .WithOne("TimeInfo")
                        .HasForeignKey("Project1.Models.TimeInfo", "TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
